# Generated by Django 5.0 on 2023-12-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0023_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPersonalizadoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('mensaje', models.CharField(max_length=650)),
            ],
            options={
                'verbose_name_plural': 'Pedidos_Personalizados_App',
            },
        ),
    ]
